version: '3.5'

networks:
  reactor:
    external: true

services:
  # Application
  base-siret-server:
    build:
      context: .
      dockerfile: Dockerfile.jvm
    container_name: baseSiret
    ports:
      - "8082:8080"
    depends_on:
      - basesiret-postgres
    environment:
      - DATABASE_SERVER_NAME=basesiret-postgres
    networks:
      - reactor
    deploy:
      resources:
        limits:
          cpus: '0.50'
          memory: 512M
        reservations:
          cpus: '0.25'
          memory: 128M
  # Bases de donnée
  basesiret-postgres:
    build:
      context: ./data/postgresql
      dockerfile: Dockerfile
    ports:
      - "5433:5433"
    restart: always
    environment:
      POSTGRES_PASSWORD: password2
      POSTGRES_DB: demoDB
      POSTGRES_USER: user2
    command: -p 5433
    volumes:
      - pgbaseSiret:/var/lib/postgresql/data
      # - ./data/postgresql/data:/data
      # - ./data/postgresql/sql/10_initStructure.sql:/docker-entrypoint-initdb.d/10_initStructure.sql
      # - ./data/postgresql/sql/99_init.sql:/docker-entrypoint-initdb.d/99_init.sql
    networks:
      - reactor
    deploy:
      resources:
        limits:
          cpus: '0.50'
          memory: 512M
        reservations:
          cpus: '0.25'
          memory: 128M
volumes: 
     pgbaseSiret:
        external: true
        name: baseSiret
